#!/usr/bin/env bash
set -euo pipefail

# Smoke test: compare ah-ah-ah token counts against the Claude API.
#
# Usage:
#   ./scripts/gen-token-fixtures.sh
#
# Requires: claude CLI with valid auth, jq, cargo (builds the count example)
#
# Sends each test string as a prompt, compares ah-ah-ah's count of that
# string against the API's `input_tokens` (user message tokens only,
# excludes cached system prompt).

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FIXTURES_DIR="$PROJECT_DIR/tests/fixtures"
mkdir -p "$FIXTURES_DIR"
OUT="$FIXTURES_DIR/claude_token_counts.json"

# Build the count example
echo "Building ah-ah-ah count example..."
cargo build --example count --manifest-path "$PROJECT_DIR/Cargo.toml" 2>/dev/null
COUNT_BIN="$PROJECT_DIR/target/debug/examples/count"

# Test corpus
declare -a TEST_STRINGS=(
  "Hello, world!"
  "The quick brown fox jumps over the lazy dog."
  "fn main() { println!(\"Hello, world!\"); }"
  "| Name | Age |\n|------|-----|\n| Alice | 30 |"
  "こんにちは世界"
  "🌍🚀✨"
  "The price is \$42.99 for 3 items (total: \$128.97)."
  "GET /api/v2/users?limit=100&offset=0 HTTP/1.1"
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
  "    if let Some(x) = maybe_value {\n        process(x);\n    }"
  "SELECT u.name, COUNT(*) FROM users u JOIN orders o ON u.id = o.user_id GROUP BY u.name;"
  "error[E0308]: mismatched types expected \`String\`, found \`&str\`"
  "https://example.com/path/to/resource?query=value&other=123#fragment"
  "2026-03-16T14:30:00.000Z"
  "The Aho-Corasick algorithm constructs a finite-state automaton from a set of patterns."
  "{\"name\": \"test\", \"values\": [1, 2, 3], \"nested\": {\"key\": \"value\"}}"
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  "    fn count(&self, text: &str, raw_count: &dyn Fn(&str) -> usize) -> usize {"
)

# --- Baseline: measure constant overhead ---
echo "Measuring baseline overhead..."
CLAUDE_CMD=(
  claude --print
    --output-format json
    --no-session-persistence
    --system-prompt "Reply with OK."
    --tools ""
    --disable-slash-commands
    --plugin-dir "$PROJECT_DIR/no-plugins"
    --settings '{}'
    --setting-sources local
    -
)

baseline_response=$(
  echo "x" | \
  MAX_THINKING_TOKENS=0 \
  CLAUDECODE="" \
  DISABLE_PROMPT_CACHING=1 \
  ANTHROPIC_API_KEY="" \
  "${CLAUDE_CMD[@]}" 2>/dev/null
) || { echo "FATAL: baseline failed" >&2; exit 1; }

# "x" = 1 token. Overhead = input_tokens - 1.
baseline_total=$(echo "$baseline_response" | jq -r '.usage.input_tokens // 0')
OVERHEAD=$((baseline_total - 1))
echo "Baseline input_tokens=$baseline_total, overhead=$OVERHEAD"
echo ""

printf "%-60s  %6s  %6s  %6s\n" "TEXT" "AH-AH" "API" "DELTA"
printf "%-60s  %6s  %6s  %6s\n" "----" "-----" "---" "-----"

results="[]"
total=${#TEST_STRINGS[@]}
i=0
pass=0
fail=0

for text in "${TEST_STRINGS[@]}"; do
  i=$((i + 1))

  # Count with ah-ah-ah
  local_count=$(echo -n "$text" | "$COUNT_BIN")

  # Send to Claude API, extract input_tokens (subtract overhead)
  response=$(
    echo "$text" | \
    MAX_THINKING_TOKENS=0 \
    CLAUDECODE="" \
    DISABLE_PROMPT_CACHING=1 \
    ANTHROPIC_API_KEY="" \
    claude --print \
      --output-format json \
      --no-session-persistence \
      --system-prompt "Reply with OK." \
      --tools "" \
      --disable-slash-commands \
      --plugin-dir "$PROJECT_DIR/no-plugins" \
      --settings '{}' \
      --setting-sources local \
      - 2>/dev/null
  ) || {
    printf "%-60s  %6d  %6s  %6s\n" "${text:0:60}" "$local_count" "FAIL" "-"
    fail=$((fail + 1))
    continue
  }

  # Save raw response for debugging
  echo "$response" > "$FIXTURES_DIR/$i.json"

  raw_api=$(echo "$response" | jq -r '.usage.input_tokens // 0')
  api_count=$((raw_api - OVERHEAD))
  delta=$((local_count - api_count))

  if [ "$delta" -ge 0 ]; then
    sign="+"
  else
    sign=""
  fi

  printf "%-60s  %6d  %6d  %s%d\n" "${text:0:60}" "$local_count" "$api_count" "$sign" "$delta"
  pass=$((pass + 1))

  # Build fixture entry
  entry=$(jq -n \
    --arg text "$text" \
    --argjson local_count "$local_count" \
    --argjson api_count "$api_count" \
    --argjson delta "$delta" \
    '{text: $text, local_count: $local_count, api_count: $api_count, delta: $delta}'
  )
  results=$(echo "$results" | jq --argjson entry "$entry" '. + [$entry]')
done

# Save fixtures
jq -n \
  --arg generated "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --argjson fixtures "$results" \
  --argjson overhead "$OVERHEAD" \
  '{
    _comment: "Generated by scripts/gen-token-fixtures.sh",
    generated: $generated,
    overhead: $overhead,
    fixtures: $fixtures
  }' > "$OUT"

echo ""
echo "Passed: $pass  Failed: $fail  Total: $total"
echo "Fixtures: $OUT"
